Repository 8848digital/erpnext, pull requests merged in 2024-11, with the labels that each got.

#523 fix:issue-521
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
Labels: needs-tests

#533 fix: error on expired_batches in stock entry
  erpnext/stock/doctype/stock_entry/stock_entry.py
Labels: needs-tests

#540 fix: error test_variant_work_order
  erpnext/manufacturing/doctype/bom/bom.py
Labels: needs-tests

#553 feat: Payment Discount Term
  erpnext/accounts/doctype/discount_terms/__init__.py
  erpnext/accounts/doctype/discount_terms/discount_terms.json
  erpnext/accounts/doctype/discount_terms/discount_terms.py
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/payment_term/payment_term.json
  erpnext/accounts/doctype/payment_term/payment_term.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/public/js/controllers/transaction.js
Labels: needs-tests

#542 fix: Expected GLE Op Issue Fix For Test Case test_repost_accounting_e…
  erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py
Labels: On Hold

#524 Report seperation from erpnext to sales commission app
  erpnext/accounts/report/sales_partners_commission/__init__.py
  erpnext/accounts/report/sales_partners_commission/sales_partners_commission.json
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/report/sales_partner_target_variance_based_on_item_group/__init__.py
  erpnext/selling/report/sales_partner_target_variance_based_on_item_group/item_group_wise_sales_target_variance.py
  erpnext/selling/report/sales_partner_target_variance_based_on_item_group/sales_partner_target_variance_based_on_item_group.js
  erpnext/selling/report/sales_partner_target_variance_based_on_item_group/sales_partner_target_variance_based_on_item_group.json
  erpnext/selling/report/sales_partner_target_variance_based_on_item_group/sales_partner_target_variance_based_on_item_group.py
  erpnext/selling/report/sales_partner_target_variance_based_on_item_group/test_sales_partner_target_variance_based_on_item_group.py
  erpnext/selling/report/sales_person_target_variance_based_on_item_group/__init__.py
  erpnext/selling/report/sales_person_target_variance_based_on_item_group/sales_person_target_variance_based_on_item_group.js
  erpnext/selling/report/sales_person_target_variance_based_on_item_group/sales_person_target_variance_based_on_item_group.json
  erpnext/selling/report/sales_person_target_variance_based_on_item_group/sales_person_target_variance_based_on_item_group.py
  erpnext/selling/report/sales_person_target_variance_based_on_item_group/test_sales_person_target_variance_based_on_item_group.py
  erpnext/selling/report/sales_person_wise_transaction_summary/__init__.py
  erpnext/selling/report/sales_person_wise_transaction_summary/sales_person_wise_transaction_summary.js
  erpnext/selling/report/sales_person_wise_transaction_summary/sales_person_wise_transaction_summary.json
  erpnext/selling/report/sales_person_wise_transaction_summary/sales_person_wise_transaction_summary.py
  erpnext/setup/doctype/sales_partner/README.md
  erpnext/setup/doctype/sales_partner/__init__.py
  erpnext/setup/doctype/sales_partner/sales_partner.js
  erpnext/setup/doctype/sales_partner/sales_partner.json
  erpnext/setup/doctype/sales_partner/sales_partner.py
  erpnext/setup/doctype/sales_partner/test_records.json
  erpnext/setup/doctype/sales_partner/test_sales_partner.py
  erpnext/setup/doctype/sales_person/README.md
  erpnext/setup/doctype/sales_person/__init__.py
  erpnext/setup/doctype/sales_person/sales_person.js
  erpnext/setup/doctype/sales_person/sales_person.json
  erpnext/setup/doctype/sales_person/sales_person.py
  erpnext/setup/doctype/sales_person/sales_person_dashboard.py
  erpnext/setup/doctype/sales_person/sales_person_tree.js
  erpnext/setup/doctype/sales_person/test_records.json
  erpnext/setup/doctype/sales_person/test_sales_person.py
Labels: Accounts, Stock, Assets, Selling, Buying, CRM, Projects

#560 fix: Error in test 'test_01_basic_functions' in Repost Accounting Ledger
  erpnext/accounts/doctype/payment_entry/payment_entry.py
Labels: needs-tests

#562 feat: Payment Entry
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/payment_term/payment_term.json
  erpnext/accounts/doctype/payment_term/payment_term.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
Labels: needs-tests

#563 fix: Error in test 'test_01_basic_functions' in Repost Accounting Ledger
  erpnext/accounts/doctype/payment_entry/payment_entry.py
Labels: needs-tests

#559 fix: error on click of finish in wo
  erpnext/stock/doctype/stock_entry/stock_entry.py
Labels: needs-tests

#575 feat: Open Item Management Feature Addition
  erpnext/accounts/doctype/account/account.json
  erpnext/accounts/doctype/account/account.py
  erpnext/accounts/doctype/gl_entry/gl_entry.json
  erpnext/accounts/doctype/gl_entry/gl_entry.py
  erpnext/accounts/doctype/gl_entry_allocation/__init__.py
  erpnext/accounts/doctype/gl_entry_allocation/gl_entry_allocation.json
  erpnext/accounts/doctype/gl_entry_allocation/gl_entry_allocation.py
  erpnext/accounts/doctype/gl_entry_reconciliation_details/__init__.py
  erpnext/accounts/doctype/gl_entry_reconciliation_details/gl_entry_reconciliation_details.json
  erpnext/accounts/doctype/gl_entry_reconciliation_details/gl_entry_reconciliation_details.py
  erpnext/accounts/doctype/gl_reconciliation_details/__init__.py
  erpnext/accounts/doctype/gl_reconciliation_details/gl_reconciliation_details.json
  erpnext/accounts/doctype/gl_reconciliation_details/gl_reconciliation_details.py
  erpnext/accounts/doctype/open_item_reconciliation/__init__.py
  erpnext/accounts/doctype/open_item_reconciliation/open_item_reconciliation.js
  erpnext/accounts/doctype/open_item_reconciliation/open_item_reconciliation.json
  erpnext/accounts/doctype/open_item_reconciliation/open_item_reconciliation.py
  erpnext/accounts/doctype/open_item_reconciliation/test_open_item_reconciliation.py
  erpnext/accounts/report/open_item/__init__.py
  erpnext/accounts/report/open_item/open_item.js
  erpnext/accounts/report/open_item/open_item.json
  erpnext/accounts/report/open_item/open_item.py
  erpnext/hooks.py
Labels: Enhancement

#583 fix: Advance Payment Issue Fix
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#595 fix:issue-594
  erpnext/stock/serial_batch_bundle.py
Labels: Stock, needs-tests

#600 feat: Payment Term- Phase 2
  erpnext/accounts/doctype/discount_terms/discount_terms.json
  erpnext/accounts/doctype/discount_terms/discount_terms.py
  erpnext/accounts/doctype/payment_entry/payment_entry.js
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
Labels: needs-tests

#614 fix: error while reinstalling the erpnext with out project module
  erpnext/setup/default_energy_point_rules.py
Labels: needs-tests

#616 feat: Phase 2
  erpnext/accounts/doctype/discount_terms/discount_terms.json
  erpnext/accounts/doctype/discount_terms/discount_terms.py
  erpnext/accounts/doctype/payment_entry/payment_entry.js
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Labels: needs-tests

#623 remove: item assets remove from erpnext
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice_dashboard.py
  erpnext/stock/doctype/item/item.js
  erpnext/stock/doctype/item/item.json
  erpnext/stock/doctype/item/item.py
  erpnext/stock/get_item_details.py
Labels: Stock, needs-tests

#618 fix: error on fetching items in stock reconciliation
  erpnext/stock/report/batch_wise_balance_history/batch_wise_balance_history.py
Labels: needs-tests

#622 fix: correction in groupby condition in get_linked_payments_for_doc method's query
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py
Labels: needs-tests

#633 Budget feature request
  erpnext/accounts/doctype/budget_amendment/budget_amendment.py
  erpnext/accounts/doctype/budget_entry/budget_entry.json
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure.py
  erpnext/accounts/doctype/zero_budget/zero_budget.json
  erpnext/stock/doctype/material_request/material_request.py
Labels: needs-tests

#635 fix: fix get_item_details for asset
  erpnext/stock/get_item_details.py
Labels: Stock, needs-tests

#639 Gl closing fixed
  erpnext/accounts/doctype/gl_closing/gl_closing.js
  erpnext/accounts/doctype/gl_closing/gl_closing.py
Labels: needs-tests

#647 fix: gl_closing
  erpnext/accounts/doctype/gl_closing/gl_closing.py
Labels: needs-tests

#649 fix: fixed erpnext apis to support asset functionalities
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/buying/doctype/purchase_order/purchase_order.py
  erpnext/controllers/buying_controller.py
  erpnext/stock/doctype/material_request/material_request.py
Labels: Buying, needs-tests

#646 fix: System Error When Unreconciling Payment via Purchase Invoice
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py
Labels: needs-tests

#640 fix: project seperation
  erpnext/accounts/doctype/budget/budget.js
  erpnext/accounts/doctype/budget/budget.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/stock_controller.py
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
Labels: Accounts, Stock, needs-tests

#659 feat: fixtures Add
  erpnext/hooks.py
Labels: needs-tests

#658 fix: Issue on cancel of Purchase Invoice and Sales Invoice
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#642 fix: Error in Bank Reconcilitaion balance calculation for Internal Transfer Payment Entries
  erpnext/accounts/doctype/bank_transaction/bank_transaction.py
Labels: needs-tests

#656 fix: taxes and charges issue
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#664 fix: dunning nonetype error
  erpnext/accounts/doctype/dunning/dunning.py
Labels: needs-tests

#669 Zero
  erpnext/accounts/doctype/budget_amendment/budget_amendment.js
  erpnext/accounts/doctype/budget_amendment/budget_amendment.json
  erpnext/accounts/doctype/budget_amendment/budget_amendment.py
  erpnext/accounts/doctype/budget_entry/budget_entry.json
  erpnext/accounts/doctype/budget_entry/budget_entry.py
  erpnext/accounts/doctype/budget_transfer/budget_transfer.js
  erpnext/accounts/doctype/budget_transfer/budget_transfer.json
  erpnext/accounts/doctype/budget_transfer/budget_transfer.py
  erpnext/accounts/doctype/wbs_budget/wbs_budget.json
  erpnext/accounts/doctype/wbs_monthly_distribution/wbs_monthly_distribution.js
  erpnext/accounts/doctype/wbs_monthly_distribution/wbs_monthly_distribution.json
  erpnext/accounts/doctype/wbs_monthly_distribution/wbs_monthly_distribution.py
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure.json
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure.py
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure_list.js
  erpnext/accounts/doctype/zero_budget/zero_budget.js
  erpnext/accounts/doctype/zero_budget/zero_budget.json
  erpnext/accounts/doctype/zero_budget/zero_budget.py
Labels: needs-tests

#674 fix: SQL Query Fix for function get_accounts_where_value_is_booked
  erpnext/stock/doctype/warehouse/warehouse.py
Labels: needs-tests

#675 fix: serial and batch manual assignment
  erpnext/accounts/doctype/purchase_invoice_item/purchase_invoice_item.json
  erpnext/accounts/doctype/purchase_invoice_item/purchase_invoice_item.py
  erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
  erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.py
  erpnext/stock/doctype/stock_reconciliation_item/stock_reconciliation_item.json
  erpnext/stock/doctype/stock_reconciliation_item/stock_reconciliation_item.py
Labels: needs-tests

#680 fix:Removed source fields from erpnext
  erpnext/stock/doctype/delivery_note/delivery_note.json
  erpnext/stock/doctype/delivery_note/delivery_note.py
Labels: needs-tests

#671 fix: Corrected some queries for issue 661
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#686 feat: report_budget
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure.js
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure.json
  erpnext/accounts/doctype/work_breakdown_structure/work_breakdown_structure_tree.js
  erpnext/accounts/report/actual_line_items/__init__.py
  erpnext/accounts/report/actual_line_items/actual_line_items.js
  erpnext/accounts/report/actual_line_items/actual_line_items.json
  erpnext/accounts/report/actual_line_items/actual_line_items.py
  erpnext/accounts/report/actual_line_items/ali_columns.py
  erpnext/accounts/report/budget_entry/__init__.py
  erpnext/accounts/report/budget_entry/budget_entry.js
  erpnext/accounts/report/budget_entry/budget_entry.json
  erpnext/accounts/report/budget_entry/budget_entry.py
  erpnext/accounts/report/budget_entry/budget_entry_columns.py
  erpnext/accounts/report/commited_line_item/__init__.py
  erpnext/accounts/report/commited_line_item/cli_columns.py
  erpnext/accounts/report/commited_line_item/commited_line_item.js
  erpnext/accounts/report/commited_line_item/commited_line_item.json
  erpnext/accounts/report/commited_line_item/commited_line_item.py
  erpnext/accounts/report/wbs_drilldown/__init__.py
  erpnext/accounts/report/wbs_drilldown/wbs_drilldown.js
  erpnext/accounts/report/wbs_drilldown/wbs_drilldown.json
  erpnext/accounts/report/wbs_drilldown/wbs_drilldown.py
  erpnext/accounts/report/wbs_drilldown/wbs_drilldown_methods.py
  erpnext/hooks.py
Labels: needs-tests

#683 535 purchase receipt1
  erpnext/accounts/utils.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
Labels: Accounts

#696 remove: assets functionality remove from erpnext
  erpnext/accounts/doctype/accounts_settings/accounts_settings.json
  erpnext/accounts/doctype/accounts_settings/accounts_settings.py
  erpnext/accounts/doctype/finance_book/finance_book_dashboard.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice_dashboard.py
  erpnext/accounts/general_ledger.py
  erpnext/manufacturing/doctype/bom/bom.js
  erpnext/selling/doctype/product_bundle/product_bundle.py
  erpnext/setup/doctype/company/company.js
  erpnext/setup/doctype/company/company.json
  erpnext/setup/doctype/company/company.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt_dashboard.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/get_item_details.py
Labels: Accounts, Stock

#695 fix: Error in Territory Target Variance Based On Item Group Report
  erpnext/selling/report/territory_target_variance_based_on_item_group/territory_target_variance_based_on_item_group.py
Labels: needs-tests

#709 removing-the-crm-folder-from-crm
  erpnext/crm/__init__.py
  erpnext/crm/crm_dashboard/crm/crm.json
  erpnext/crm/dashboard_chart/incoming_leads/incoming_leads.json
  erpnext/crm/dashboard_chart/lead_source/lead_source.json
  erpnext/crm/dashboard_chart/opportunities_via_campaigns/opportunities_via_campaigns.json
  erpnext/crm/dashboard_chart/opportunity_trends/opportunity_trends.json
  erpnext/crm/dashboard_chart/territory_wise_opportunity_count/territory_wise_opportunity_count.json
  erpnext/crm/dashboard_chart/territory_wise_sales/territory_wise_sales.json
  erpnext/crm/dashboard_chart/won_opportunities/won_opportunities.json
  erpnext/crm/module_onboarding/crm/crm.json
  erpnext/crm/number_card/new_lead_(last_1_month)/new_lead_(last_1_month).json
  erpnext/crm/number_card/new_opportunity_(last_1_month)/new_opportunity_(last_1_month).json
  erpnext/crm/number_card/open_opportunity/open_opportunity.json
  erpnext/crm/number_card/won_opportunity_(last_1_month)/won_opportunity_(last_1_month).json
  erpnext/crm/onboarding/crm/crm.json
  erpnext/crm/onboarding_step/create_and_send_quotation/create_and_send_quotation.json
  erpnext/crm/onboarding_step/create_lead/create_lead.json
  erpnext/crm/onboarding_step/create_opportunity/create_opportunity.json
  erpnext/crm/onboarding_step/crm_settings/crm_settings.json
  erpnext/crm/onboarding_step/introduction_to_crm/introduction_to_crm.json
  erpnext/crm/report/__init__.py
  erpnext/crm/report/lead_conversion_time/__init__.py
  erpnext/crm/report/lead_conversion_time/lead_conversion_time.js
  erpnext/crm/report/lead_conversion_time/lead_conversion_time.json
  erpnext/crm/report/lead_conversion_time/lead_conversion_time.py
  erpnext/crm/report/lost_opportunity/__init__.py
  erpnext/crm/report/lost_opportunity/lost_opportunity.js
  erpnext/crm/report/lost_opportunity/lost_opportunity.json
  erpnext/crm/report/lost_opportunity/lost_opportunity.py
  erpnext/crm/utils.py
  erpnext/crm/workspace/crm/crm.json
Labels: CRM, needs-tests

#699 fix:reverting-the-make-contact-method-to-erpnext-make-contact-method
  erpnext/selling/doctype/customer/customer.py
Labels: needs-tests

#705 feat: Added Clearing Date Functionality in Payment Reconcilieation to put the posting date of GL Entry and PL Entry
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.js
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.json
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py
  erpnext/accounts/doctype/payment_reconciliation_record/payment_reconciliation_record.json
  erpnext/accounts/general_ledger.py
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#701 feat: added a condition for project
  erpnext/accounts/doctype/payment_request/payment_request.json
  erpnext/accounts/doctype/payment_request/payment_request.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/buying/doctype/purchase_order/purchase_order.py
  erpnext/controllers/stock_controller.py
  erpnext/hooks.py
  erpnext/manufacturing/doctype/production_plan/production_plan.py
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py
Labels: Stock, needs-tests

#713 Removed-crm-folder-from-erpnext-to-crm-app
  erpnext/crm/__init__.py
  erpnext/crm/crm_dashboard/crm/crm.json
  erpnext/crm/dashboard_chart/incoming_leads/incoming_leads.json
  erpnext/crm/dashboard_chart/lead_source/lead_source.json
  erpnext/crm/dashboard_chart/opportunities_via_campaigns/opportunities_via_campaigns.json
  erpnext/crm/dashboard_chart/opportunity_trends/opportunity_trends.json
  erpnext/crm/dashboard_chart/territory_wise_opportunity_count/territory_wise_opportunity_count.json
  erpnext/crm/dashboard_chart/territory_wise_sales/territory_wise_sales.json
  erpnext/crm/dashboard_chart/won_opportunities/won_opportunities.json
  erpnext/crm/module_onboarding/crm/crm.json
  erpnext/crm/number_card/new_lead_(last_1_month)/new_lead_(last_1_month).json
  erpnext/crm/number_card/new_opportunity_(last_1_month)/new_opportunity_(last_1_month).json
  erpnext/crm/number_card/open_opportunity/open_opportunity.json
  erpnext/crm/number_card/won_opportunity_(last_1_month)/won_opportunity_(last_1_month).json
  erpnext/crm/onboarding/crm/crm.json
  erpnext/crm/onboarding_step/create_and_send_quotation/create_and_send_quotation.json
  erpnext/crm/onboarding_step/create_lead/create_lead.json
  erpnext/crm/onboarding_step/create_opportunity/create_opportunity.json
  erpnext/crm/onboarding_step/crm_settings/crm_settings.json
  erpnext/crm/onboarding_step/introduction_to_crm/introduction_to_crm.json
  erpnext/crm/report/__init__.py
  erpnext/crm/report/lead_conversion_time/__init__.py
  erpnext/crm/report/lead_conversion_time/lead_conversion_time.js
  erpnext/crm/report/lead_conversion_time/lead_conversion_time.json
  erpnext/crm/report/lead_conversion_time/lead_conversion_time.py
  erpnext/crm/report/lost_opportunity/__init__.py
  erpnext/crm/report/lost_opportunity/lost_opportunity.js
  erpnext/crm/report/lost_opportunity/lost_opportunity.json
  erpnext/crm/report/lost_opportunity/lost_opportunity.py
  erpnext/crm/utils.py
  erpnext/crm/workspace/crm/crm.json
Labels: CRM, needs-tests

#706 Pre prod v15
  erpnext/__init__.py
  erpnext/accounts/doctype/account/account.py
  erpnext/accounts/doctype/bank_account/bank_account.json
  erpnext/accounts/doctype/bank_clearance/bank_clearance.py
  erpnext/accounts/doctype/bank_clearance/test_bank_clearance.py
  erpnext/accounts/doctype/cost_center_allocation/test_cost_center_allocation.py
  erpnext/accounts/doctype/journal_entry/journal_entry.js
  erpnext/accounts/doctype/journal_entry/journal_entry.py
  erpnext/accounts/doctype/journal_entry/test_journal_entry.py
  erpnext/accounts/doctype/payment_entry/payment_entry.js
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/payment_entry_reference/payment_entry_reference.json
  erpnext/accounts/doctype/payment_entry_reference/payment_entry_reference.py
  erpnext/accounts/doctype/payment_reconciliation/test_payment_reconciliation.py
  erpnext/accounts/doctype/payment_request/payment_request.js
  erpnext/accounts/doctype/payment_request/payment_request.json
  erpnext/accounts/doctype/payment_request/payment_request.py
  erpnext/accounts/doctype/payment_request/test_payment_request.py
  erpnext/accounts/doctype/pos_closing_entry/pos_closing_entry.js
  erpnext/accounts/doctype/pos_invoice/pos_invoice.js
  erpnext/accounts/doctype/pos_invoice/pos_invoice.py
  erpnext/accounts/doctype/pricing_rule/pricing_rule.json
  erpnext/accounts/doctype/pricing_rule/test_pricing_rule.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/accounts/doctype/tax_rule/tax_rule.py
  erpnext/accounts/general_ledger.py
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
  erpnext/accounts/report/balance_sheet/balance_sheet.py
  erpnext/accounts/report/cash_flow/cash_flow.py
  erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py
  erpnext/accounts/report/general_and_payment_ledger_comparison/general_and_payment_ledger_comparison.py
  erpnext/accounts/report/general_ledger/general_ledger.py
  erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py
  erpnext/accounts/utils.py
  erpnext/buying/doctype/purchase_order/purchase_order.js
  erpnext/buying/doctype/purchase_order/purchase_order.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/selling_controller.py
  erpnext/manufacturing/doctype/bom_creator/bom_creator.json
  erpnext/manufacturing/doctype/plant_floor/plant_floor.js
  erpnext/manufacturing/doctype/plant_floor/plant_floor.json
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/patches/v14_0/update_reports_with_range.py
  erpnext/public/js/bom_configurator/bom_configurator.bundle.js
  erpnext/public/js/controllers/transaction.js
  erpnext/public/js/templates/visual_plant_floor_template.html
  erpnext/public/js/utils/sales_common.js
  erpnext/public/scss/erpnext.scss
  erpnext/selling/doctype/sales_order/sales_order.js
  erpnext/selling/page/point_of_sale/pos_item_cart.js
  erpnext/setup/doctype/transaction_deletion_record/transaction_deletion_record.py
  erpnext/stock/dashboard_chart/oldest_items/oldest_items.json
  erpnext/stock/doctype/quality_inspection/quality_inspection.js
  erpnext/stock/doctype/quality_inspection/quality_inspection.py
  erpnext/stock/report/stock_balance/stock_balance.js
  erpnext/stock/report/stock_balance/stock_balance.py
Labels: Accounts, Selling, CRM

#718 Wizard-completion-erpnext-issues-on-installing-new-site
  erpnext/setup/setup_wizard/operations/install_fixtures.py
Labels: needs-tests

#720 feat: Unreconcile from Payment Reconciliation Record
  erpnext/accounts/doctype/payment_reconciliation_allocation_records/payment_reconciliation_allocation_records.json
  erpnext/accounts/doctype/payment_reconciliation_record/payment_reconciliation_record.js
  erpnext/accounts/doctype/payment_reconciliation_record/payment_reconciliation_record.json
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py
  erpnext/public/js/utils/unreconcile.js
Labels: needs-tests

#731 Hooks
  erpnext/hooks.py
  erpnext/stock/doctype/item/item.js
Labels: needs-tests

#734 Update hooks.py
  erpnext/hooks.py
Labels: needs-tests

#736 feat: PO / PI
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/buying/doctype/purchase_order/purchase_order.py
Labels: needs-tests

#742 Bug 726
  erpnext/accounts/doctype/payment_entry/payment_entry.py
Labels: needs-tests

#739 feat: removed project dependency from budget module
  erpnext/accounts/doctype/budget/budget.json
  erpnext/budget/doctype/budget_amendment/budget_amendment.js
  erpnext/budget/doctype/budget_amendment/budget_amendment.json
  erpnext/budget/doctype/budget_amendment/budget_amendment.py
  erpnext/budget/doctype/budget_entry/budget_entry.json
  erpnext/budget/doctype/budget_entry/budget_entry.py
  erpnext/budget/doctype/budget_transfer/budget_transfer.js
  erpnext/budget/doctype/budget_transfer/budget_transfer.json
  erpnext/budget/doctype/budget_transfer/budget_transfer.py
  erpnext/budget/doctype/wbs_budget/wbs_budget.json
  erpnext/budget/doctype/work_breakdown_structure/work_breakdown_structure.js
  erpnext/budget/doctype/work_breakdown_structure/work_breakdown_structure.json
  erpnext/budget/doctype/work_breakdown_structure/work_breakdown_structure.py
  erpnext/budget/doctype/zero_budget/zero_budget.js
  erpnext/budget/doctype/zero_budget/zero_budget.json
  erpnext/budget/doctype/zero_budget/zero_budget.py
  erpnext/projects/doctype/project/project.json
  erpnext/projects/doctype/project/project.py
Labels: needs-tests

#753 fix: typo error
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Labels: needs-tests

#761 Fixed: Error on Portal
  erpnext/controllers/website_list_for_contact.py
Labels: needs-tests

#774 648 - Implement clearing date to appear on UnReconcile for each source docs
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py
  erpnext/public/js/utils/unreconcile.js
Labels: needs-tests

#775 fix: vat_audit_report
  erpnext/regional/report/vat_audit_report/vat_audit_report.py
Labels: needs-tests
