Repository 8848digital/erpnext, pull requests merged in 2024-10, with the labels that each got.

#104 fix: fix the tree view error in task and accout doctype
  erpnext/accounts/utils.py
  erpnext/projects/doctype/task/task.py
Labels: Accounts, needs-tests

#109 fix: updated the get_item_details query date format condition as per postgres.
  erpnext/manufacturing/doctype/work_order/work_order.py
Labels: needs-tests

#112 Not able to submit Asset Capitalization showing error
  erpnext/controllers/stock_controller.py
Labels: Stock, needs-tests

#115 fix: Purchase Order Analysis Report Fix
  erpnext/buying/report/purchase_order_analysis/purchase_order_analysis.py
Labels: needs-tests

#123 fix: purchase_receipt_submit_issue
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
  erpnext/stock/stock_ledger.py
Labels: Stock, needs-tests

#125 Sales order analysis report
  erpnext/accounts/report/sales_partners_commission/sales_partners_commission.json
  erpnext/selling/report/sales_order_analysis/sales_order_analysis.py
Labels: needs-tests

#119 fix: error while submitiing and cancelling stock_reconciliation
  erpnext/controllers/stock_controller.py
  erpnext/stock/stock_ledger.py
Labels: Stock, needs-tests

#124 fix: job card get_operations api error
  erpnext/manufacturing/doctype/job_card/job_card.py
Labels: needs-tests

#126 fix: item dashboard error resolved
  erpnext/stock/doctype/item/item.py
Labels: needs-tests

#131 fix: available_stock_for_packing_items report
  erpnext/selling/report/available_stock_for_packing_items/available_stock_for_packing_items.py
Labels: needs-tests

#130 fix: conflict error solved
  erpnext/controllers/stock_controller.py
Labels: Stock, needs-tests

#134 fix: production_planning_report
  erpnext/manufacturing/report/production_planning_report/production_planning_report.py
Labels: needs-tests

#135 fix: pending_so_items_for_purchase_request_report
  erpnext/selling/report/pending_so_items_for_purchase_request/pending_so_items_for_purchase_request.py
Labels: needs-tests

#143 fix: resolved issue for delivery note and purchase receipt on submit …
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
Labels: needs-tests

#140 fix: updated syntax in query
  erpnext/selling/report/sales_person_wise_transaction_summary/sales_person_wise_transaction_summary.py
Labels: needs-tests

#141 fix: requested_items_to_order_and_receive_report
  erpnext/buying/report/requested_items_to_order_and_receive/requested_items_to_order_and_receive.py
Labels: needs-tests

#142 fix: sales pipeline analytics
  erpnext/crm/report/sales_pipeline_analytics/sales_pipeline_analytics.py
Labels: needs-tests

#144 fix: fix the Sales Funnel page
  erpnext/selling/page/sales_funnel/sales_funnel.py
Labels: needs-tests

#149 fix: fix the Opportunity Summary by Sales Stage Report
  erpnext/crm/report/opportunity_summary_by_sales_stage/opportunity_summary_by_sales_stage.py
Labels: needs-tests

#138 fix:97-asset-after-submission-of-asset-maintenance-showing-error
  erpnext/assets/doctype/asset_maintenance/asset_maintenance.py
Labels: needs-tests

#155 fix: job card get_current_operation_data api error
  erpnext/manufacturing/doctype/job_card/job_card.py
Labels: needs-tests

#160 fix: error on submitting the document
  erpnext/stock/doctype/stock_reservation_entry/stock_reservation_entry.py
Labels: needs-tests

#161 fix: server error while creating sales person
  erpnext/setup/doctype/sales_person/sales_person.py
Labels: needs-tests

#163 fix: uom issue in pricing rule
  erpnext/accounts/doctype/pricing_rule/pricing_rule.py
Labels: needs-tests

#164 fix: Unable to submit Quality Inspection entry
  erpnext/stock/doctype/quality_inspection/quality_inspection.py
Labels: needs-tests

#165 fix: sales payment summary report
  erpnext/accounts/report/sales_payment_summary/sales_payment_summary.py
Labels: needs-tests

#168 fix:Purchase Register Report
  erpnext/accounts/report/purchase_register/purchase_register.py
Labels: needs-tests

#170 fix: gross profit fix
  erpnext/accounts/report/gross_profit/gross_profit.py
Labels: needs-tests

#171 fix: error while creating stock entry from work order
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/stock/utils.py
Labels: Stock, needs-tests

#173 fix: Request for Raw Material creation through sales order create but…
  erpnext/manufacturing/doctype/production_plan/production_plan.py
Labels: needs-tests

#177 fix: batch wise balance history report
  erpnext/stock/report/batch_wise_balance_history/batch_wise_balance_history.py
Labels: needs-tests

#180 fix: Unable to submit Subcontracting Receipt entry
  erpnext/controllers/subcontracting_controller.py
Labels: needs-tests

#182 fix:selecting Batch from Select batch Dialog in delivery note
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
Labels: needs-tests

#183 fix: While applying group by filter on Item-wise Purchase Register Re…
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
Labels: needs-tests

#185 fix: Return / Debit note: Unable to create Return / Debit note from P…
  erpnext/controllers/sales_and_purchase_return.py
Labels: needs-tests

#187 179-while-creation-of-packing-slip-as-we-select-delivery-note-showing…
  erpnext/stock/doctype/packing_slip/packing_slip.py
Labels: needs-tests

#193 fix: While applying filter as supplier in Purchase Invoice Trends Rep…
  erpnext/controllers/trends.py
Labels: needs-tests

#189 fix: Payment Reconcilation
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#188 fix: fix the batch number filters in stock ledger report
  erpnext/stock/report/stock_ledger/stock_ledger.py
Labels: needs-tests

#194 fix: Delivery Note Report Filters
  erpnext/controllers/trends.py
Labels: needs-tests

#199 fix: error while creating payment entry from po
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/utils.py
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#198 fix: remove the bill date from the PR and DN trend because it is not …
  erpnext/controllers/trends.py
Labels: needs-tests

#197 fix: datetime issue in web form on customer login
  erpnext/support/doctype/service_level_agreement/service_level_agreement.py
Labels: needs-tests

#202 fix:Not able to create delivery note for Serialize Item. #151
  erpnext/stock/serial_batch_bundle.py
Labels: Stock, needs-tests

#211 chore: convert like into ilike for the case sensitive in postgres
  erpnext/controllers/queries.py
Labels: needs-tests

#207 fix: Date Difference Condition Fix
  erpnext/setup/doctype/sales_person/sales_person.py
Labels: needs-tests

#205 fix: company date subtract sql query fix for postgressql
  erpnext/setup/doctype/company/company.py
Labels: needs-tests

#212 fix: fix the get_row_materail_transfer error
  erpnext/manufacturing/doctype/production_plan/production_plan.py
Labels: needs-tests

#213 fix: while opening the POS getting error
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Labels: needs-tests

#215 fix: while saving the POS Closing Entry doctype, getting the error
  erpnext/accounts/doctype/pos_closing_entry/pos_closing_entry.py
Labels: needs-tests

#218 fix: company doctype handle concurrent transaction error on get_timeline_data
  erpnext/setup/doctype/company/company.py
Labels: needs-tests

#226 fix: get_payment_entries_issue
  erpnext/accounts/doctype/bank_clearance/bank_clearance.py
Labels: needs-tests

#227 fix: Chart of Accounts Importer Bug Fix
  erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py
Labels: needs-tests

#245 fix:230-bug-merge-item-by-renaming-item-with-existing-item
  erpnext/stock/doctype/item/item.py
Labels: needs-tests

#237 fix: 221 Account Head Search Fix
  erpnext/controllers/queries.py
Labels: needs-tests

#258 fix: Payment Reconciliation Tool functionality is not working Properly
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#261 Fixed: Null error while creating single and multiple variants
  erpnext/utilities/product.py
Labels: needs-tests

#263 Revert "Fixed: Null error while creating single and multiple variants"
  erpnext/utilities/product.py
Labels: needs-tests

#265 Fixed: Null error while creating single and multiple variants
  erpnext/utilities/product.py
Labels: needs-tests

#264 fix: Stock Balance Report
  erpnext/stock/report/stock_balance/stock_balance.py
Labels: needs-tests

#257 stock_ageing
  erpnext/stock/report/stock_ageing/stock_ageing.py
Labels: needs-tests

#256 fix: stock_projected_qty_report
  erpnext/stock/report/stock_projected_qty/stock_projected_qty.py
Labels: needs-tests

#269 268-error-while-creating-a-new-customer-when-assigning-a-lead-lead-cr…
  erpnext/selling/doctype/customer/customer.py
Labels: needs-tests

#271 fix: Error while generating the Bank Reconciliation Statement Report
  erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py
Labels: needs-tests

#276 fix: Report POS Register - if group by filter is selected as 'Payment…
  erpnext/accounts/report/pos_register/pos_register.py
Labels: needs-tests

#279 fix: While applying filter of Order type against the Sales order in Sales Analytics Report showing error
  erpnext/selling/report/sales_analytics/sales_analytics.py
Labels: needs-tests

#283 fix: resolved erros in test_accounting_dimension
  erpnext/accounts/doctype/repost_accounting_ledger/repost_accounting_ledger.py
Labels: needs-tests

#286 fix: Report Bank Clearence Summary - error while generating Bank Clearence Summary
  erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py
Labels: needs-tests

#290 fix: error in query \ndate/time field value out of range
  erpnext/stock/get_item_details.py
Labels: Stock, needs-tests

#292 fix: fixed error in monthly budget crossed
  erpnext/accounts/doctype/budget/budget.py
Labels: needs-tests

#293 fix: date conversion using parser instead of strptime
  erpnext/stock/get_item_details.py
Labels: Stock, needs-tests

#299 fix: error while creating dunning from sales invoice
  erpnext/accounts/doctype/dunning/dunning.py
Labels: needs-tests

#300 fix: error on check show_future_payments
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
Labels: needs-tests

#310 fix: While applying filter of customer with item against the Company …
  erpnext/controllers/trends.py
Labels: needs-tests

#311 fix: error on show_gl_balance checkbox
  erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.py
Labels: needs-tests

#318 fix: errors fix in test ledger health
  erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py
Labels: needs-tests

#320 fix: Report Customer Ledger Summary - Error while generating the customer ledger summary report
  erpnext/accounts/report/customer_ledger_summary/customer_ledger_summary.py
Labels: needs-tests

#316 feat: set status for assets created from purchase receipt
  erpnext/controllers/buying_controller.py
Labels: Buying, needs-tests

#323 Revert "feat: set status for assets created from purchase receipt"
  erpnext/controllers/buying_controller.py
Labels: Buying, needs-tests

#328 Fixed: Able to split in Asset
  erpnext/assets/doctype/asset/asset.py
Labels: needs-tests

#332 fix: Report Dimension-wise Accounts Balance Report - error while gene…
  erpnext/accounts/report/dimension_wise_accounts_balance_report/dimension_wise_accounts_balance_report.py
Labels: needs-tests

#342 329 payment terms status for sales order report showing error
  erpnext/selling/report/payment_terms_status_for_sales_order/payment_terms_status_for_sales_order.py
Labels: needs-tests

#344 Revert "329 payment terms status for sales order report showing error"
  erpnext/selling/report/payment_terms_status_for_sales_order/payment_terms_status_for_sales_order.py
Labels: needs-tests

#354 fix: Stock and Account Value Comparison Report showing error
  erpnext/stock/report/stock_and_account_value_comparison/stock_and_account_value_comparison.py
Labels: needs-tests

#358 fix: Available Batch Report Showing Error
  erpnext/stock/report/available_batch_report/available_batch_report.py
Labels: needs-tests

#360 feat: GL Closing
  erpnext/accounts/doctype/accounts_closing_table/__init__.py
  erpnext/accounts/doctype/accounts_closing_table/accounts_closing_table.json
  erpnext/accounts/doctype/accounts_closing_table/accounts_closing_table.py
  erpnext/accounts/doctype/gl_closing/__init__.py
  erpnext/accounts/doctype/gl_closing/gl_closing.js
  erpnext/accounts/doctype/gl_closing/gl_closing.json
  erpnext/accounts/doctype/gl_closing/gl_closing.py
  erpnext/accounts/doctype/gl_closing/test_gl_closing.py
  erpnext/accounts/doctype/gl_closing_details/__init__.py
  erpnext/accounts/doctype/gl_closing_details/gl_closing_details.json
  erpnext/accounts/doctype/gl_closing_details/gl_closing_details.py
  erpnext/accounts/install.py
  erpnext/hooks.py
Labels: Accounts

#365 fix: Report Lost Opportunity - error while generating the Lost Opportunity Report
  erpnext/crm/report/lost_opportunity/lost_opportunity.py
Labels: needs-tests

#359 fix: Total Stock Summary Report showing error
  erpnext/stock/report/total_stock_summary/total_stock_summary.py
Labels: needs-tests

#363 Fixed: pr selection in asset
  erpnext/controllers/queries.py
Labels: needs-tests

#371 Fixed: Bug error in Quotation Trend report
  erpnext/controllers/trends.py
Labels: needs-tests

#372 fix: error on selecting based_on as customer
  erpnext/controllers/trends.py
Labels: needs-tests

#375 fix: Stock Ledger Invariant Check Report Showing Error
  erpnext/stock/report/stock_ledger_invariant_check/stock_ledger_invariant_check.py
Labels: needs-tests

#369 329-payment-terms-status-for-sales-order-report-showing-error-1_issue
  erpnext/selling/report/payment_terms_status_for_sales_order/payment_terms_status_for_sales_order.py
Labels: needs-tests

#382 fix: Stock Entry - Error while selecting the batch number in the add serial Nos dialog in the stock entry child table
  erpnext/controllers/queries.py
Labels: needs-tests

#386 fix : Cannot able to view customer 8848
  erpnext/accounts/party.py
Labels: Accounts, needs-tests

#387 fix: FIFO Queue vs Qty After Transaction Comparison Report Showing Error
  erpnext/stock/report/fifo_queue_vs_qty_after_transaction_comparison/fifo_queue_vs_qty_after_transaction_comparison.py
Labels: needs-tests

#391 feat: Removed report Asset_Depreciations_And_Balances and Asset_Depre…
  erpnext/accounts/report/asset_depreciation_ledger/__init__.py
  erpnext/accounts/report/asset_depreciation_ledger/asset_depreciation_ledger.js
  erpnext/accounts/report/asset_depreciation_ledger/asset_depreciation_ledger.json
  erpnext/accounts/report/asset_depreciation_ledger/asset_depreciation_ledger.py
  erpnext/accounts/report/asset_depreciations_and_balances/__init__.py
  erpnext/accounts/report/asset_depreciations_and_balances/asset_depreciations_and_balances.js
  erpnext/accounts/report/asset_depreciations_and_balances/asset_depreciations_and_balances.json
  erpnext/accounts/report/asset_depreciations_and_balances/asset_depreciations_and_balances.py
Labels: needs-tests

#394 feat: added condition to query for postgre
  erpnext/stock/reorder_item.py
Labels: Stock, needs-tests

#398 fix: Filters Issue Fix for Serial Batch Summary
  erpnext/stock/report/serial_and_batch_summary/serial_and_batch_summary.py
Labels: needs-tests

#389 feat: assets validate_cwip_accounts migrate from erpnext
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
Labels: needs-tests

#396 fix: error fixed in test_monthly_budget_crossed_stop2
  erpnext/accounts/doctype/budget/budget.py
Labels: needs-tests

#401 fix: test_closing_balance_with_dimensions_and_test_reposting_entry gr…
  erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py
Labels: needs-tests

#402 fix: error on selecting cost_center in report
  erpnext/accounts/report/utils.py
Labels: needs-tests

#411 fix: Filter Issue Fix for Item Wise Sales Register Report
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
Labels: needs-tests

#414 fix: schedeuler failed - error while executing the scheduler
  erpnext/accounts/utils.py
  erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py
Labels: Accounts, needs-tests

#416 fix: While Applying filter of purchase invoice in Billed Items To Be Received Report showing error
  erpnext/accounts/report/billed_items_to_be_received/billed_items_to_be_received.py
Labels: needs-tests

#420 fix: scheduler failed - error while executing the auto_create_fiscal_…
  erpnext/accounts/doctype/fiscal_year/fiscal_year.py
Labels: needs-tests

#425 Fix : While Add item name Book in items in BOM doctype it show error
  erpnext/manufacturing/doctype/bom/bom.py
Labels: needs-tests

#427 fix: fixed error in test_partial_allocation_on_advance_as_liability
  erpnext/accounts/general_ledger.py
Labels: Accounts, needs-tests

#436 fix: scheduler failed - error while executing the auto_create_exchang…
  erpnext/accounts/doctype/exchange_rate_revaluation/exchange_rate_revaluation.py
Labels: needs-tests

#437 fix: Work Order Stock Report Showing Error
  erpnext/manufacturing/report/work_order_stock_report/work_order_stock_report.py
Labels: needs-tests

#439 fix: error fixed in test_01_unreconcile_invoice
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py
Labels: needs-tests

#444 fix : When typing the item name manually in the BOM Doctype, an error…
  erpnext/manufacturing/doctype/bom/bom.py
Labels: needs-tests

#441 feat: removing assets dependency for buying controller and purchase receipt
  erpnext/controllers/buying_controller.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.js
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt_dashboard.py
  erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
  erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.py
Labels: Buying, needs-tests

#449 fix: Resolve the work order stock report filter issue
  erpnext/manufacturing/report/work_order_stock_report/work_order_stock_report.py
Labels: needs-tests

#468 fix: Update get_expense sql queries
  erpnext/controllers/queries.py
Labels: needs-tests

#473 fix: modified issue date sql query issue
  erpnext/buying/doctype/purchase_order/purchase_order.py
Labels: needs-tests

#474 fix: Error in Repost Item Valuation while restarting
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#467 FR|Created new app sales commission and added fields of Sales invoice…
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/modules.txt
  erpnext/sales_commission/__init__.py
  erpnext/selling/doctype/customer/customer.json
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/stock/doctype/delivery_note/delivery_note.json
  erpnext/stock/doctype/delivery_note/delivery_note.py
Labels: needs-tests

#476 fix: restore assets buying controller
  erpnext/controllers/buying_controller.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
Labels: Buying, needs-tests

#477 fix: scheduler failed - error while executing the scheduler accounts_controller.update_invoice_status
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#479 Issue 478
  erpnext/controllers/queries.py
Labels: needs-tests

#480 fix: When attempting to reserve stock for an item in the sales order,…
  erpnext/controllers/queries.py
Labels: needs-tests

#484 fix: error in party details
  erpnext/accounts/party.py
Labels: Accounts, needs-tests

#485 fix: packing slip - error while selecting item in child table which is in packing slip doctype
  erpnext/stock/doctype/packing_slip/packing_slip.py
Labels: needs-tests

#492 fix: scheduler failed - error while executing the process_statement_o…
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py
Labels: needs-tests

#491 469-an-error-occurs-when-trying-to-create-a-sales-order-from-a-quotat…
  erpnext/selling/doctype/quotation/quotation.py
Labels: needs-tests

#493 feat: accounting dimension in asset movement
  erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py
  erpnext/accounts/doctype/journal_entry/journal_entry.py
  erpnext/controllers/buying_controller.py
Labels: Buying, needs-tests

#500 fix: issue-498
  erpnext/controllers/item_variant.py
Labels: Stock, needs-tests

#495 fix: issue-494
  erpnext/stock/doctype/item/item.py
Labels: needs-tests

#502 fix: fixed error in test_reserved_qty_for_partial_delivery
  erpnext/selling/doctype/sales_order/sales_order.py
Labels: needs-tests

#511 fix: asset location not getting fetched due to accounting dimension
  erpnext/controllers/buying_controller.py
Labels: Buying, needs-tests
