Repository 8848digital/erpnext, pull requests merged in 2024-12, with the labels that each got.

#779 fix: item tax template validation
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#789 fix: migration issue in accounts controller
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#790 Revert "fix: item tax template validation"
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#795 feat: System Allows Recording Multicurrency Transactions Against INR …
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Labels: needs-tests

#792 fix: Update Sql Query as per Postgres
  erpnext/templates/pages/rfq.py
Labels: needs-tests

#810 fix:Rmemoved sales partner type doctype from erpnext
  erpnext/setup/setup_wizard/operations/install_fixtures.py
Labels: needs-tests

#804 fix: Issue-756
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
Labels: needs-tests

#812 fix: Update comparision value in query builder
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#815 fix: validate item tax template
  erpnext/controllers/taxes_and_totals.py
Labels: Accounts, needs-tests

#823 fix: accounts_controller.py fix
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#822 Issue 818 fix
  erpnext/controllers/queries.py
Labels: needs-tests

#826 feat: added test case for pricing rule
  erpnext/stock/doctype/delivery_note/test_delivery_note.py
Labels: Accounts

#830 Import fixes
  erpnext/controllers/sales_and_purchase_return.py
Labels: needs-tests

#838 fix: Sales invoice not able to submit.
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#835 fix: issue_831,issue_833
  erpnext/manufacturing/report/process_loss_report/process_loss_report.py
  erpnext/quality_management/report/review/review.json
Labels: needs-tests

#844 fix: create dunning in si overdue day itself
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Labels: needs-tests

#843 fix: Update sql query for user_permission
  erpnext/controllers/queries.py
Labels: needs-tests

#846 Fixed: Error in UAE VAT 201 report
  erpnext/regional/report/uae_vat_201/uae_vat_201.py
Labels: needs-tests

#856 fix: Removed duplicate doc_event hook from hooks.py
  erpnext/hooks.py
Labels: needs-tests

#862 fix: issue in like change to like
  erpnext/controllers/queries.py
Labels: needs-tests

#866 fix: sql query in patch files
  erpnext/patches/v14_0/update_stock_uom_in_work_order_item.py
  erpnext/patches/v15_0/set_is_exchange_gain_loss_in_payment_entry_deductions.py
Labels: needs-tests

#870 issue-852
  erpnext/patches/v14_0/update_closing_balances.py
Labels: needs-tests, temporary solution

#869 fix:issue 850
  erpnext/accounts/general_ledger.py
Labels: Accounts, needs-tests

#860 Commits pre prod
  erpnext/__init__.py
  erpnext/accounts/doctype/payment_entry/payment_entry.js
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py
  erpnext/accounts/doctype/payment_request/payment_request_list.js
  erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
  erpnext/accounts/doctype/pricing_rule/pricing_rule.py
  erpnext/accounts/doctype/pricing_rule/utils.py
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.json
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py
  erpnext/accounts/doctype/process_statement_of_accounts_cc/__init__.py
  erpnext/accounts/doctype/process_statement_of_accounts_cc/process_statement_of_accounts_cc.json
  erpnext/accounts/doctype/process_statement_of_accounts_cc/process_statement_of_accounts_cc.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice_list.js
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
  erpnext/accounts/report/financial_statements.py
  erpnext/accounts/report/general_ledger/general_ledger.py
  erpnext/accounts/report/gross_profit/gross_profit.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/sales_and_purchase_return.py
  erpnext/manufacturing/doctype/bom/bom.js
  erpnext/manufacturing/doctype/bom/bom.py
  erpnext/patches.txt
  erpnext/patches/v15_0/enable_allow_existing_serial_no.py
  erpnext/patches/v15_0/update_cc_in_process_statement_of_accounts.py
  erpnext/public/js/queries.js
  erpnext/selling/doctype/quotation_item/quotation_item.json
  erpnext/selling/page/point_of_sale/pos_past_order_summary.js
  erpnext/stock/doctype/delivery_note/delivery_note.py
  erpnext/stock/doctype/material_request/material_request.js
  erpnext/stock/doctype/pick_list/pick_list_list.js
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.js
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
  erpnext/stock/doctype/stock_settings/stock_settings.json
  erpnext/subcontracting/doctype/subcontracting_order/subcontracting_order_list.js
  erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt_list.js
  erpnext/templates/includes/issue_row.html
  erpnext/templates/includes/projects/project_row.html
  erpnext/templates/includes/transaction_row.html
  erpnext/templates/pages/timelog_info.html
Labels: Accounts

#876 fix: batch serial format in item
  erpnext/stock/doctype/batch/batch.py
  erpnext/stock/doctype/item/item.py
Labels: needs-tests

#877 fix: added a item query in pos invoice file
  erpnext/accounts/doctype/pos_invoice/pos_invoice.py
Labels: needs-tests

#895 feat: update v15 dec 23
  erpnext/__init__.py
  erpnext/accounts/doctype/repost_accounting_ledger/repost_accounting_ledger.py
  erpnext/manufacturing/doctype/bom/bom.js
Labels: needs-tests

#896 fix: to fetch Advances paid, issue-891
  erpnext/controllers/accounts_controller.py
Labels: Accounts, needs-tests

#907 Update v15 pre prod
  .github/helper/documentation.py
  erpnext/__init__.py
  erpnext/accounts/doctype/account/chart_of_accounts/verified/se_kontoplan_BAS_2024_with_account_number.json
  erpnext/accounts/doctype/bank_account/bank_account.py
  erpnext/accounts/doctype/bank_clearance/bank_clearance.py
  erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
  erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py
  erpnext/accounts/report/financial_statements.py
  erpnext/accounts/report/gross_profit/gross_profit.py
  erpnext/accounts/report/tax_withholding_details/tax_withholding_details.py
  erpnext/buying/doctype/purchase_order/purchase_order.js
  erpnext/buying/doctype/purchase_order/purchase_order.py
  erpnext/buying/doctype/purchase_order/test_purchase_order.py
  erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
  erpnext/buying/doctype/purchase_order_item/purchase_order_item.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/stock_controller.py
  erpnext/controllers/subcontracting_controller.py
  erpnext/controllers/tests/test_subcontracting_controller.py
  erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.js
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/selling/page/point_of_sale/pos_controller.js
  erpnext/selling/page/point_of_sale/pos_item_selector.js
  erpnext/setup/doctype/quotation_lost_reason/quotation_lost_reason.json
  erpnext/setup/setup_wizard/data/country_wise_tax.json
  erpnext/stock/dashboard_chart/warehouse_wise_stock_value/warehouse_wise_stock_value.json
  erpnext/stock/deprecated_serial_batch.py
  erpnext/stock/doctype/closing_stock_balance/closing_stock_balance.json
  erpnext/stock/doctype/pick_list/pick_list.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/serial_and_batch_bundle/test_serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.js
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/doctype/stock_entry/test_stock_entry.py
  erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.json
  erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py
  erpnext/stock/doctype/stock_reconciliation/test_stock_reconciliation.py
  erpnext/stock/serial_batch_bundle.py
  erpnext/stock/stock_ledger.py
  erpnext/subcontracting/doctype/subcontracting_order/subcontracting_order.js
  erpnext/subcontracting/doctype/subcontracting_order/subcontracting_order.py
  erpnext/subcontracting/doctype/subcontracting_order/test_subcontracting_order.py
  erpnext/subcontracting/doctype/subcontracting_order_item/subcontracting_order_item.json
  erpnext/subcontracting/doctype/subcontracting_order_item/subcontracting_order_item.py
  erpnext/subcontracting/doctype/subcontracting_order_service_item/subcontracting_order_service_item.json
  erpnext/subcontracting/doctype/subcontracting_order_service_item/subcontracting_order_service_item.py
Labels: Accounts, Stock
