Repository 8848digital/erpnext, pull requests merged in 2024-09, with the labels that each got.

#12 fix: fix the limit and offset issue
  erpnext/controllers/queries.py
Labels: needs-tests

#20 Limit andoffset issue
  erpnext/controllers/queries.py
Labels: accounts, stock, assets, selling, buying, crm, projects

#31 fix :fix the sales order submition bug
  erpnext/stock/stock_balance.py
Labels: stock, needs-tests

#33 fix: creation of mr fetch items from bom
  erpnext/manufacturing/doctype/bom/bom.py
Labels: needs-tests

#37 fix: fix the sales order submition bug
  erpnext/stock/stock_balance.py
Labels: stock, needs-tests

#36 fix: fix the from_date and to_date issue in report
  erpnext/projects/report/daily_timesheet_summary/daily_timesheet_summary.py
Labels: needs-tests

#35 fix: fix the cost center error in sales invoice
  erpnext/controllers/queries.py
Labels: needs-tests

#45 fix: issue of creation MR from BOM when fetch_explode_bom is checked
  erpnext/manufacturing/doctype/bom/bom.py
Labels: needs-tests

#46 fix: fix the cheques_and_deposits_incorrectly_cleared report error
  erpnext/accounts/report/cheques_and_deposits_incorrectly_cleared/cheques_and_deposits_incorrectly_cleared.py
Labels: needs-tests

#47 fix: error on clicking stop button in MR
  erpnext/stock/doctype/material_request/material_request.py
Labels: needs-tests

#51 fix: while creation of material transfer entry through create button …
  erpnext/stock/stock_ledger.py
Labels: stock, needs-tests

#62 fix: resolved inventory dimension save issue
  erpnext/stock/doctype/inventory_dimension/inventory_dimension.py
Labels: needs-tests

#73 fix: purchase_issue_save_issue
  erpnext/controllers/buying_controller.py
Labels: buying, needs-tests

#76 fix: fix the sales_order_trends_report
  erpnext/controllers/trends.py
Labels: needs-tests

#81 fix: fix the stock ledger report
  erpnext/stock/doctype/inventory_dimension/inventory_dimension.py
Labels: needs-tests

#84 fix: error on submit and cancel of sales invoice
  erpnext/accounts/general_ledger.py
  erpnext/accounts/utils.py
  erpnext/setup/doctype/company/company.py
Labels: accounts, needs-tests

#86 fix: fix the tree view error in location and company doctype
  erpnext/assets/doctype/location/location.py
  erpnext/setup/doctype/company/company.py
Labels: needs-tests

#101 fix: Resolved user doctype issue on Lead Details report
  erpnext/crm/report/lead_details/lead_details.py
Labels: needs-tests

#100 Project issue while open #55
  erpnext/projects/doctype/project/project.py
Labels: needs-tests
