Repository 8848digital/erpnext, pull requests merged in 2025-04, with the labels that each got.

#2001 fix: issue-1992 point of sale item add issue
  erpnext/selling/page/point_of_sale/point_of_sale.py
  erpnext/selling/page/point_of_sale/pos_item_selector.js
Labels: needs-tests

#2007 Commits from 14th march to 27th march
  .github/workflows/label-base-on-title.yml
  erpnext/__init__.py
  erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py
  erpnext/accounts/doctype/bank_clearance/bank_clearance.py
  erpnext/accounts/doctype/gl_entry/gl_entry.json
  erpnext/accounts/doctype/journal_entry/journal_entry.py
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/payment_schedule/payment_schedule.json
  erpnext/accounts/doctype/payment_schedule/payment_schedule.py
  erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
  erpnext/accounts/doctype/repost_accounting_ledger/repost_accounting_ledger.py
  erpnext/accounts/doctype/repost_accounting_ledger/test_repost_accounting_ledger.py
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/accounts/general_ledger.py
  erpnext/accounts/party.py
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
  erpnext/accounts/utils.py
  erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/subcontracting_controller.py
  erpnext/controllers/website_list_for_contact.py
  erpnext/manufacturing/doctype/bom/bom.py
  erpnext/manufacturing/doctype/job_card/job_card.json
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/production_plan/production_plan.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/patches.txt
  erpnext/patches/v15_0/recalculate_amount_difference_field.py
  erpnext/patches/v15_0/rename_subcontracting_fields.py
  erpnext/patches/v15_0/update_payment_schedule_fields_in_invoices.py
  erpnext/public/js/controllers/buying.js
  erpnext/public/js/controllers/transaction.js
  erpnext/public/js/utils.js
  erpnext/public/js/utils/party.js
  erpnext/regional/report/uae_vat_201/test_uae_vat_201.py
  erpnext/regional/report/uae_vat_201/uae_vat_201.py
  erpnext/selling/doctype/sales_order/sales_order.py
  erpnext/selling/doctype/sales_order/test_sales_order.py
  erpnext/setup/doctype/transaction_deletion_record/transaction_deletion_record.py
  erpnext/stock/deprecated_serial_batch.py
  erpnext/stock/doctype/batch/batch.py
  erpnext/stock/doctype/item_default/item_default.json
  erpnext/stock/doctype/material_request/material_request.py
  erpnext/stock/doctype/pick_list/pick_list.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt_dashboard.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/doctype/quality_inspection/quality_inspection.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.js
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json
  erpnext/stock/doctype/stock_ledger_entry/test_stock_ledger_entry.py
  erpnext/stock/report/batch_wise_balance_history/batch_wise_balance_history.py
  erpnext/stock/serial_batch_bundle.py
Labels: Accounts, Stock

#2030 Fixed: multiple test cases
  erpnext/accounts/utils.py
Labels: bug, Accounts, needs-tests, Common Issue

#2036 fix: fixed failed test case test_deferred_expense_via_journal_entry
  erpnext/accounts/deferred_revenue.py
Labels: Accounts, needs-tests

#2043 Pre prod develop
  erpnext/accounts/deferred_revenue.py
  erpnext/accounts/doctype/journal_entry/test_journal_entry.py
  erpnext/accounts/doctype/payment_entry/test_payment_entry.py
  erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/buying/doctype/purchase_order/test_purchase_order.py
  erpnext/buying/report/purchase_order_analysis/purchase_order_analysis.py
  erpnext/stock/doctype/stock_entry/test_stock_entry.py
Labels: Accounts

#2054 Fixed: test case
  erpnext/controllers/accounts_controller.py
  erpnext/stock/doctype/material_request/test_material_request.py
Labels: Accounts

#2057 Fixed: ModuleNotFoundError
  erpnext/telephony/doctype/call_log/call_log.py
Labels: needs-tests

#2070 fix: multiple ple created while reconciliing multiple documents
  erpnext/accounts/doctype/payment_reconciliation_record/payment_reconciliation_record.py
Labels: needs-tests

#2078 fix: Fixed contact creation issue and BOM test case
  erpnext/telephony/doctype/call_log/call_log.py
Labels: needs-tests

#2102 Pre prod develop into Pre-prod
  erpnext/telephony/doctype/call_log/call_log.py
Labels: needs-tests

#2065 fix: fixed dependency error - TC_B_037
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
Labels: needs-tests

#2106 fix: fix issue no 1994
  erpnext/accounts/doctype/bank_transaction/bank_transaction.py
Labels: needs-tests

#2142 Pre prod develop into Pre-prod
  erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py
  erpnext/controllers/accounts_controller.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
Labels: Accounts

#2146 fix : Process Statement Of Accounts | test_auto_email_for_process_soa…
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py
Labels: needs-tests

#2141 fix: Fixed project app dependency on company dashboard
  erpnext/setup/doctype/company/company.py
Labels: needs-tests

#2153 fix:Company | test_demo_data | psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "tabPurchase Invoice"#1953
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
Labels: needs-tests

#2172 Fix:Isusue with valuation rate as None
  erpnext/stock/stock_ledger.py
Labels: Stock, needs-tests

#2173 Pre prod develop
  erpnext/accounts/doctype/journal_entry/test_journal_entry.py
  erpnext/stock/doctype/material_request/test_material_request.py
  erpnext/stock/stock_ledger.py
Labels: Stock

#2189 fix: fix the syntax issue of the sales order analysis report
  erpnext/selling/report/sales_order_analysis/sales_order_analysis.py
Labels: needs-tests

#2259 invoice_fix_push
  erpnext/accounts/doctype/journal_entry/journal_entry.json
  erpnext/accounts/doctype/journal_entry/journal_entry.py
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.json
  erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py
  erpnext/accounts/general_ledger.py
  erpnext/accounts/utils.py
Labels: Accounts, needs-tests

#2279 Pre prod develop
  .github/workflows/postgres-test.yml
  erpnext/controllers/queries.py
Labels: needs-tests
