Repository 8848digital/erpnext, pull requests merged in 2025-08, with the labels that each got.

#2818 chore(release): Bumped to Version 15.63.0
  erpnext/__init__.py
  erpnext/accounts/doctype/pos_invoice/pos_invoice.py
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py
  erpnext/accounts/doctype/process_statement_of_accounts/test_process_statement_of_accounts.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py
  erpnext/accounts/doctype/tax_withholding_category/test_tax_withholding_category.py
  erpnext/accounts/party.py
  erpnext/accounts/report/customer_ledger_summary/customer_ledger_summary.py
  erpnext/buying/utils.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/buying_controller.py
  erpnext/controllers/selling_controller.py
  erpnext/controllers/stock_controller.py
  erpnext/patches.txt
  erpnext/patches/v14_0/update_full_name_in_contract.py
  erpnext/patches/v15_0/rename_group_by_to_categorize_by_in_custom_reports.py
  erpnext/patches/v15_0/set_cancelled_status_to_cancelled_pos_invoice.py
  erpnext/public/js/controllers/transaction.js
  erpnext/selling/doctype/quotation/quotation.json
  erpnext/selling/page/point_of_sale/pos_past_order_summary.js
  erpnext/stock/dashboard_chart/warehouse_wise_stock_value/warehouse_wise_stock_value.json
  erpnext/stock/doctype/material_request/material_request.js
  erpnext/stock/doctype/material_request/material_request.py
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
  erpnext/stock/stock_ledger.py
  erpnext/utilities/transaction_base.py
Labels: Accounts, Stock, Selling, Buying

#2824 fix: bug on report delivered items to be billed on load
  erpnext/accounts/report/delivered_items_to_be_billed/delivered_items_to_be_billed.py
Labels: needs-tests

#2827 test: Test Coverage for Bank Transaction Upload functionality, validating CSV/XLSX file processing, header mapping, bank entry creation, and error handling mechanisms.
  erpnext/accounts/doctype/bank_transaction/test_bank_transaction_upload.py
Labels: skip-release-notes

#2829 test: test coverage for General Ledger reporting functionality, validating filter validation, account currency handling, condition building, data processing, and various reporting scenarios.
  erpnext/accounts/report/general_ledger/test_general_ledger.py
Labels: skip-release-notes
