Repository 8848digital/erpnext, pull requests merged in 2025-09, with the labels that each got.

#2841 test: added a file
  erpnext/accounts/report/received_items_to_be_billed/test_received_items_to_be_billed.py
Labels: skip-release-notes

#2835 test: test coverage for Inactive Sales Items Report functionality, validating territory-based filtering, item grouping, sales data analysis, and inactive item identification across both Sales Invoice and Sales Order data sources
  erpnext/accounts/report/inactive_sales_items/test_inactive_sales_items.py
Labels: skip-release-notes

#2836 test: add new test cases for Payment Request and Payment Order
  erpnext/accounts/doctype/payment_order/payment_order.py
  erpnext/accounts/doctype/payment_order/test_payment_order.py
  erpnext/accounts/doctype/payment_request/test_payment_request.py
  erpnext/accounts/doctype/payment_schedule/payment_schedule.py
  erpnext/accounts/doctype/payment_term/payment_term.py
  erpnext/accounts/doctype/payment_terms_template/payment_terms_template.py
  erpnext/accounts/doctype/payment_terms_template_detail/payment_terms_template_detail.py
Labels: skip-release-notes

#2837 test: Test Coverage for Item Wise Purchase Report functionality, validating filter handling, grouping options, additional column integration, and conditional query building for purchase data analysis.
  erpnext/accounts/report/item_wise_purchase_register/test_item_wise_purchase_register.py
Labels: skip-release-notes

#2840 Refactor: Centralize get_or_create_fiscal_year method in utils.py
  erpnext/accounts/doctype/bank_transaction/test_bank_transaction.py
  erpnext/accounts/doctype/exchange_rate_revaluation/test_exchange_rate_revaluation.py
  erpnext/accounts/doctype/invoice_discounting/test_invoice_discounting.py
  erpnext/accounts/doctype/payment_entry/test_payment_entry.py
  erpnext/accounts/doctype/payment_ledger_entry/test_payment_ledger_entry.py
  erpnext/accounts/doctype/pricing_rule/test_pricing_rule.py
  erpnext/accounts/doctype/process_deferred_accounting/test_process_deferred_accounting.py
  erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/accounts/doctype/subscription/test_subscription.py
  erpnext/accounts/doctype/tax_rule/test_tax_rule.py
  erpnext/buying/doctype/purchase_order/test_purchase_order.py
  erpnext/manufacturing/doctype/blanket_order/test_blanket_order.py
  erpnext/manufacturing/doctype/bom/test_bom.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/selling/doctype/sales_order/test_sales_order.py
  erpnext/stock/doctype/delivery_note/test_delivery_note.py
  erpnext/stock/doctype/material_request/test_material_request.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/doctype/quality_inspection/test_quality_inspection.py
  erpnext/stock/doctype/stock_entry/test_stock_entry.py
  erpnext/stock/doctype/stock_ledger_entry/test_stock_ledger_entry.py
  erpnext/stock/doctype/warehouse/test_warehouse.py
  erpnext/stock/report/available_batch_report/test_available_batch_report.py
  erpnext/stock/report/delivery_note_trends/test_delivery_note_trends.py
  erpnext/stock/report/item_price_stock/test_item_price_stock.py
  erpnext/stock/report/stock_and_account_value_comparison/test_stock_and_account_value_comparison.py
  erpnext/stock/report/stock_projected_qty/test_stock_projected_qty.py
  erpnext/stock/report/total_stock_summary/test_total_stock_summary.py
  erpnext/stock/utils.py
Labels: Stock, skip-release-notes

#2843 test: Item-wise Sales Register Report functionality, validating basic report execution, grouping options, conditional filtering, tax calculations, and advanced query building for detailed sales analysis.
  erpnext/accounts/report/item_wise_sales_register/test_item_wise_sales_register.py
Labels: skip-release-notes

#2844 test: Open Item Report check functionality, validating filter validation, account currency handling, GL entry processing, grouping options, and full report execution flow for accounts receivable/payable analysis.
  erpnext/accounts/report/open_item/test_open_item.py
Labels: skip-release-notes

#2851 test: Bank Reconciliation Statement Report functionality, validating empty filter handling, account-based reporting, balance calculations, and proper integration with general ledger entries for accurate bank statement reconciliation
  erpnext/accounts/report/bank_reconciliation_statement/test_bank_reconciliation_statement.py
Labels: skip-release-notes

#2852 chore(release): Bumped to Version 15.64.1
  erpnext/__init__.py
  erpnext/accounts/doctype/accounts_settings/accounts_settings.json
  erpnext/buying/report/purchase_order_analysis/purchase_order_analysis.js
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/taxes_and_totals.py
  erpnext/selling/doctype/sales_order/sales_order.js
  erpnext/selling/page/point_of_sale/pos_controller.js
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
  erpnext/stock/report/cogs_by_item_group/cogs_by_item_group.py
  erpnext/stock/stock_ledger.py
Labels: Accounts, Stock, needs-tests, skip-release-notes

#2856 Test: test_get_account_details_and_party_type_TC_ACC_566 for Journal …
  erpnext/accounts/doctype/journal_entry/test_journal_entry.py
Labels: skip-release-notes
