Repository 8848digital/erpnext, pull requests merged in 2025-03, with the labels that each got.

#1446 Fix: Renaming crm to custom_crm in import statments in erpnext app
  erpnext/accounts/doctype/tax_rule/test_tax_rule.py
  erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
  erpnext/buying/doctype/request_for_quotation/test_request_for_quotation.py
  erpnext/controllers/selling_controller.py
  erpnext/public/js/communication.js
  erpnext/public/js/utils/crm_activities.js
  erpnext/selling/doctype/quotation/quotation.js
  erpnext/selling/doctype/quotation/quotation.py
  erpnext/stock/doctype/delivery_note/test_delivery_note.py
  erpnext/telephony/doctype/call_log/call_log.py
Labels: Selling

#1459 Removed-Duplicate-import-in-call-log-doctype-file
  erpnext/telephony/doctype/call_log/call_log.py
Labels: needs-tests

#1286 feat: erpnext v-15 commit from 30 jan till 6th feb
  erpnext/__init__.py
  erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.js
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/pos_closing_entry/test_pos_closing_entry.py
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/doctype/subscription/subscription.py
  erpnext/accounts/report/gross_profit/gross_profit.json
  erpnext/accounts/report/gross_profit/gross_profit.py
  erpnext/accounts/report/gross_profit/test_gross_profit.py
  erpnext/buying/doctype/purchase_order/purchase_order.js
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/queries.py
  erpnext/controllers/selling_controller.py
  erpnext/controllers/stock_controller.py
  erpnext/controllers/subcontracting_controller.py
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/job_card/test_job_card.py
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.py
  erpnext/manufacturing/doctype/production_plan/production_plan.js
  erpnext/manufacturing/doctype/production_plan/production_plan.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/patches.txt
  erpnext/patches/v14_0/disable_add_row_in_gross_profit.py
  erpnext/public/js/controllers/transaction.js
  erpnext/public/scss/point-of-sale.scss
  erpnext/selling/page/point_of_sale/pos_controller.js
  erpnext/selling/page/point_of_sale/pos_past_order_summary.js
  erpnext/selling/page/point_of_sale/pos_payment.js
  erpnext/setup/doctype/employee/employee.json
  erpnext/stock/deprecated_serial_batch.py
  erpnext/stock/doctype/batch/batch.py
  erpnext/stock/doctype/closing_stock_balance/closing_stock_balance.py
  erpnext/stock/doctype/delivery_note/delivery_note.py
  erpnext/stock/doctype/delivery_note_item/delivery_note_item.json
  erpnext/stock/doctype/packing_slip/packing_slip.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/serial_and_batch_bundle/test_serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/get_item_details.py
  erpnext/stock/report/batch_wise_balance_history/batch_wise_balance_history.py
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.js
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.json
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.py
  erpnext/stock/report/stock_ageing/stock_ageing.py
  erpnext/stock/report/stock_ledger/stock_ledger.py
  erpnext/stock/serial_batch_bundle.py
  erpnext/stock/stock_ledger.py
  erpnext/stock/tests/test_get_item_details.py
Labels: Accounts, Stock, Selling

#1479 Fix: Added the decorators to the custom crm methods
  erpnext/telephony/doctype/call_log/call_log.py
Labels: needs-tests

#1480 Pre prod develop
  erpnext/__init__.py
  erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.js
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/pos_closing_entry/test_pos_closing_entry.py
  erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/accounts/doctype/subscription/subscription.py
  erpnext/accounts/report/gross_profit/gross_profit.json
  erpnext/accounts/report/gross_profit/gross_profit.py
  erpnext/accounts/report/gross_profit/test_gross_profit.py
  erpnext/buying/doctype/purchase_order/purchase_order.js
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/queries.py
  erpnext/controllers/selling_controller.py
  erpnext/controllers/stock_controller.py
  erpnext/controllers/subcontracting_controller.py
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/job_card/test_job_card.py
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.py
  erpnext/manufacturing/doctype/production_plan/production_plan.js
  erpnext/manufacturing/doctype/production_plan/production_plan.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/patches.txt
  erpnext/patches/v14_0/disable_add_row_in_gross_profit.py
  erpnext/public/js/controllers/transaction.js
  erpnext/public/scss/point-of-sale.scss
  erpnext/selling/doctype/sales_order/test_sales_order.py
  erpnext/selling/page/point_of_sale/pos_controller.js
  erpnext/selling/page/point_of_sale/pos_past_order_summary.js
  erpnext/selling/page/point_of_sale/pos_payment.js
  erpnext/setup/doctype/employee/employee.json
  erpnext/stock/deprecated_serial_batch.py
  erpnext/stock/doctype/batch/batch.py
  erpnext/stock/doctype/closing_stock_balance/closing_stock_balance.py
  erpnext/stock/doctype/delivery_note/delivery_note.py
  erpnext/stock/doctype/delivery_note_item/delivery_note_item.json
  erpnext/stock/doctype/packing_slip/packing_slip.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/doctype/quality_inspection/test_quality_inspection.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/serial_and_batch_bundle/test_serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/doctype/stock_entry/test_stock_entry.py
  erpnext/stock/get_item_details.py
  erpnext/stock/report/batch_wise_balance_history/batch_wise_balance_history.py
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.js
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.json
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.py
  erpnext/stock/report/stock_ageing/stock_ageing.py
  erpnext/stock/report/stock_ledger/stock_ledger.py
  erpnext/stock/serial_batch_bundle.py
  erpnext/stock/stock_ledger.py
  erpnext/stock/tests/test_get_item_details.py
  erpnext/telephony/doctype/call_log/call_log.py
Labels: Accounts, Stock, Selling

#1503 fix: repost item valuation - date and time issue
  erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py
Labels: needs-tests

#1546 fix: variable assignment error in TC 234,235,236
  erpnext/stock/doctype/stock_entry/stock_entry.py
Labels: needs-tests

#1460 Refactor: Add app install check & move imports to functions
  erpnext/accounts/doctype/tax_rule/test_tax_rule.py
  erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
  erpnext/buying/doctype/request_for_quotation/test_request_for_quotation.py
  erpnext/controllers/selling_controller.py
  erpnext/public/js/communication.js
  erpnext/public/js/utils/crm_activities.js
  erpnext/selling/doctype/quotation/quotation.js
  erpnext/selling/doctype/quotation/quotation.py
  erpnext/stock/doctype/delivery_note/test_delivery_note.py
  erpnext/telephony/doctype/call_log/call_log.py
Labels: Selling

#1560 Pre prod develop
  erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/accounts/doctype/tax_rule/test_tax_rule.py
  erpnext/buying/doctype/purchase_order/test_purchase_order.py
  erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
  erpnext/buying/doctype/request_for_quotation/test_request_for_quotation.py
  erpnext/controllers/selling_controller.py
  erpnext/public/js/communication.js
  erpnext/public/js/utils/crm_activities.js
  erpnext/selling/doctype/quotation/quotation.js
  erpnext/selling/doctype/quotation/quotation.py
  erpnext/selling/doctype/sales_order/test_sales_order.py
  erpnext/stock/doctype/delivery_note/test_delivery_note.py
  erpnext/stock/doctype/material_request/test_material_request.py
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/doctype/stock_entry/test_stock_entry.py
  erpnext/telephony/doctype/call_log/call_log.py
Labels: Selling

#1818 feat: add missing frappe_crm_api file
  erpnext/frappe_crm_api.py
Labels: needs-tests

#1827 feat: add missing frappe_crm_api file
  erpnext/frappe_crm_api.py
Labels: needs-tests

#1821 fix: resolved While creating Promotional Scheme getting error frappe.exceptions.ValidationError: Value for Sales Partner cannot be a list issue.
  erpnext/accounts/doctype/promotional_scheme/promotional_scheme.py
Labels: needs-tests

#1842 Issue 1521
  erpnext/accounts/doctype/promotional_scheme/promotional_scheme.py
Labels: needs-tests

#1872 fix: issue in payment reconciliation
  erpnext/accounts/doctype/payment_entry/test_payment_entry.py
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py
  erpnext/controllers/accounts_controller.py
Labels: Accounts

#1877 fix: added missing patches for version 14 and 15
  erpnext/accounts/utils.py
  erpnext/patches.txt
  erpnext/patches/v14_0/update_posting_datetime.py
  erpnext/patches/v15_0/migrate_checkbox_to_select_for_reconciliation_effect.py
  erpnext/patches/v15_0/sync_auto_reconcile_config.py
Labels: Accounts, needs-tests

#1890 fix: NegativeStockError and bad operand type for abs():tuple
  erpnext/accounts/general_ledger.py
  erpnext/manufacturing/doctype/blanket_order/test_blanket_order.py
Labels: Accounts

#1876 fix: fixed Rate is showing as 0 in report (committed line item)
  erpnext/budget/report/commited_line_item/commited_line_item.py
Labels: needs-tests

#1947 fix: added project dependency for
  erpnext/manufacturing/doctype/work_order/work_order.py
Labels: needs-tests

#1958 Item shortage report issue
  erpnext/stock/report/item_shortage_report/item_shortage_report.py
Labels: needs-tests

#1951 Incorrect serial and batch bundle issue
  erpnext/stock/report/incorrect_serial_and_batch_bundle/incorrect_serial_and_batch_bundle.py
Labels: needs-tests

#1989 Fixed: test case in dn
  erpnext/controllers/selling_controller.py
  erpnext/selling/doctype/sales_order/test_sales_order.py
Labels: Selling

#1993 fix: Fixed issue with Bank Transaction test case, resolved app depend…
  erpnext/accounts/doctype/bank_transaction/bank_transaction.json
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
Labels: needs-tests

#1995 fix: Removed project app field from Sale Order Item
  erpnext/selling/doctype/sales_order_item/sales_order_item.json
  erpnext/selling/doctype/sales_order_item/sales_order_item.py
Labels: needs-tests

#1999 fix: issue-1997 filters are not working
  erpnext/budget/report/actual_line_items/actual_line_items.js
  erpnext/budget/report/actual_line_items/actual_line_items.py
Labels: needs-tests
