Repository 8848digital/erpnext, pull requests merged in 2025-01, with the labels that each got.

#924 fix: issue-923, item_code order by issue
  erpnext/stock/doctype/material_request/material_request.py
Labels: needs-tests

#930 fix: fix the NotImplementedError
  erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py
Labels: needs-tests

#939 Issue creating new supplier
  erpnext/buying/custom_fields/supplier.json
  erpnext/buying/doctype/supplier/supplier.json
  erpnext/buying/doctype/supplier/supplier.py
  erpnext/setup/install.py
Labels: needs-tests

#932 erpnext commit from date Dec26 to jan1
  erpnext/accounts/doctype/account/account.json
  erpnext/accounts/doctype/advance_taxes_and_charges/advance_taxes_and_charges.json
  erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py
  erpnext/accounts/doctype/gl_entry/gl_entry.py
  erpnext/accounts/doctype/gl_entry/test_gl_entry.py
  erpnext/accounts/doctype/payment_entry/payment_entry.js
  erpnext/accounts/doctype/payment_entry/test_payment_entry.py
  erpnext/accounts/doctype/pos_closing_entry/closing_voucher_details.html
  erpnext/accounts/doctype/pos_closing_entry_taxes/pos_closing_entry_taxes.json
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/accounts/party.py
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
  erpnext/accounts/utils.py
  erpnext/buying/report/purchase_order_analysis/purchase_order_analysis.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/buying_controller.py
  erpnext/controllers/queries.py
  erpnext/controllers/status_updater.py
  erpnext/controllers/subcontracting_controller.py
  erpnext/controllers/taxes_and_totals.py
  erpnext/manufacturing/doctype/blanket_order/blanket_order.json
  erpnext/manufacturing/doctype/blanket_order/blanket_order.py
  erpnext/manufacturing/doctype/bom/bom_list.js
  erpnext/manufacturing/report/exponential_smoothing_forecasting/exponential_smoothing_forecasting.py
  erpnext/manufacturing/report/production_analytics/production_analytics.py
  erpnext/manufacturing/report/test_reports.py
  erpnext/public/js/bom_configurator/bom_configurator.bundle.js
  erpnext/public/js/controllers/buying.js
  erpnext/public/js/controllers/transaction.js
  erpnext/selling/page/point_of_sale/pos_controller.js
  erpnext/selling/page/point_of_sale/pos_item_cart.js
  erpnext/selling/page/point_of_sale/pos_item_details.js
  erpnext/selling/page/point_of_sale/pos_payment.js
  erpnext/setup/setup_wizard/operations/taxes_setup.py
  erpnext/stock/deprecated_serial_batch.py
  erpnext/stock/doctype/closing_stock_balance/closing_stock_balance.py
  erpnext/stock/doctype/material_request/material_request.js
  erpnext/stock/doctype/material_request/material_request.py
  erpnext/stock/doctype/material_request/material_request_list.js
  erpnext/stock/doctype/material_request/test_material_request.py
  erpnext/stock/doctype/quality_inspection/quality_inspection.json
  erpnext/stock/doctype/quality_inspection/quality_inspection.py
  erpnext/stock/doctype/serial_and_batch_bundle/test_serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/get_item_details.py
  erpnext/stock/stock_balance.py
  erpnext/stock/stock_ledger.py
  erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py
  erpnext/subcontracting/doctype/subcontracting_receipt/test_subcontracting_receipt.py
  erpnext/templates/includes/footer/footer_extension.html
  erpnext/templates/includes/order/order_taxes.html
  erpnext/templates/pages/order.html
Labels: Accounts, Stock, Buying

#944 fix: Issues in Purchase Order Process: Duplicate Material Requests an…
  erpnext/stock/doctype/material_request/material_request.py
Labels: needs-tests

#1013 fix: resolved issues While saving Payment Entry (advance) against Sal…
  erpnext/accounts/doctype/payment_entry/payment_entry.py
Labels: needs-tests

#1012 Commit 2jan 9jan
  erpnext/__init__.py
  erpnext/accounts/doctype/account/account_tree.js
  erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.js
  erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py
  erpnext/accounts/doctype/budget/budget.py
  erpnext/accounts/doctype/gl_entry/gl_entry.py
  erpnext/accounts/doctype/payment_request/payment_request.json
  erpnext/accounts/doctype/payment_request/payment_request.py
  erpnext/accounts/doctype/process_payment_reconciliation/process_payment_reconciliation.json
  erpnext/accounts/doctype/process_payment_reconciliation/process_payment_reconciliation.py
  erpnext/accounts/doctype/process_payment_reconciliation_log/process_payment_reconciliation_log.json
  erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py
  erpnext/controllers/accounts_controller.py
  erpnext/controllers/subcontracting_controller.py
  erpnext/controllers/tests/test_subcontracting_controller.py
  erpnext/manufacturing/doctype/bom/bom_item_preview.html
  erpnext/manufacturing/doctype/bom_update_tool/bom_update_tool.py
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/report/work_order_consumed_materials/work_order_consumed_materials.py
  erpnext/patches/v15_0/update_asset_status_to_work_in_progress.py
  erpnext/public/js/bank_reconciliation_tool/data_table_manager.js
  erpnext/public/js/controllers/transaction.js
  erpnext/selling/page/point_of_sale/point_of_sale.py
  erpnext/selling/page/point_of_sale/pos_item_cart.js
  erpnext/selling/page/point_of_sale/pos_item_details.js
  erpnext/selling/page/point_of_sale/pos_item_selector.js
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
  erpnext/stock/report/stock_balance/stock_balance.py
  erpnext/support/web_form/issues/issues.json
Labels: Accounts

#1021 feat:custom_bank_reconciliation_tool
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.js
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.json
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1024 1022 error on trial balance
  erpnext/accounts/report/trial_balance/trial_balance.py
Labels: needs-tests

#1017 fix: Accounts Closing Table does not exists error and item_wise_sales…
  erpnext/accounts/doctype/gl_closing/gl_closing.py
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
Labels: needs-tests

#1033 fix: get withdraw and deposit for erp transaction
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1043 fix: get withdraw and deposit for erp transaction
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1051 fix: get withdraw and deposit for erp transaction
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1052 feat: msgprint on no record found
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1063 fix: resolved issue Getting an error while creating a purchase invoice
  erpnext/accounts/doctype/gl_closing/gl_closing.py
Labels: needs-tests

#1066 fix: closing entry fix
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1067 fix:after submitting the Purchase Receipt, the rate reverts to the or…
  erpnext/accounts/doctype/pricing_rule/pricing_rule.py
Labels: needs-tests

#1070 fix: closing entry fix
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.js
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.json
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
  erpnext/accounts/doctype/journal_entry_account/journal_entry_account.py
Labels: needs-tests

#1076 fix: closing entry fix
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.js
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
  erpnext/accounts/doctype/journal_entry_account/journal_entry_account.json
Labels: needs-tests

#1086 fix: remaining amount fetch correct for allocate
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1089 fix: Purchase order filter not working in purchase order anaylis report
  erpnext/buying/report/purchase_order_analysis/purchase_order_analysis.py
Labels: needs-tests

#1112 feat: opening bal to be dynamic as per date, validation for records
  erpnext/accounts/doctype/bank_account/bank_account.json
  erpnext/accounts/doctype/bank_account/bank_account.py
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.js
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1116 Item wise sales register
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
Labels: needs-tests

#1126 feat: opening bal to be dynamic as per date, validation for records
  erpnext/accounts/doctype/bank_account/bank_account.json
  erpnext/accounts/doctype/bank_account/bank_account.py
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
  erpnext/accounts/doctype/bank_transaction/bank_transaction.py
Labels: needs-tests

#1127 feat: opening bal to be dynamic as per date, validation for records
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1130 feat: validation while creating duplicate Bank Transaction
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.js
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
  erpnext/accounts/doctype/bank_transaction/bank_transaction.py
Labels: needs-tests

#1133 feat: validation while creating duplicate Bank Transaction
  erpnext/accounts/doctype/bank_transaction/bank_transaction.js
  erpnext/accounts/doctype/bank_transaction/bank_transaction.py
Labels: needs-tests

#1098 Commit 9 to 16 jan
  erpnext/__init__.py
  erpnext/accounts/doctype/payment_entry/payment_entry.json
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/accounts/doctype/payment_entry_reference/payment_entry_reference.json
  erpnext/accounts/doctype/payment_entry_reference/payment_entry_reference.py
  erpnext/accounts/doctype/payment_reconciliation/test_payment_reconciliation.py
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
  erpnext/accounts/doctype/subscription/subscription.py
  erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
  erpnext/accounts/utils.py
  erpnext/controllers/accounts_controller.py
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/job_card/test_job_card.py
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
  erpnext/manufacturing/doctype/production_plan/test_production_plan.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/patches.txt
  erpnext/patches/v15_0/migrate_checkbox_to_select_for_reconciliation_effect.py
  erpnext/public/js/controllers/buying.js
  erpnext/public/js/controllers/transaction.js
  erpnext/selling/doctype/quotation/quotation.py
  erpnext/selling/doctype/quotation/test_quotation.py
  erpnext/selling/doctype/sales_order/test_sales_order.py
  erpnext/selling/page/point_of_sale/point_of_sale.py
  erpnext/setup/doctype/company/company.json
  erpnext/setup/doctype/company/company.py
  erpnext/stock/doctype/batch/batch.py
  erpnext/stock/doctype/delivery_note/delivery_note.py
  erpnext/stock/doctype/delivery_note/test_delivery_note.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/serial_no/serial_no.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/get_item_details.py
  erpnext/stock/stock_ledger.py
Labels: Accounts, Stock

#1149 fix: index error
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.js
  erpnext/accounts/doctype/bank_reconciliation_tool_erpnext/bank_reconciliation_tool_erpnext.py
Labels: needs-tests

#1150 fix: PI and SI trends report group by issue
  erpnext/controllers/trends.py
Labels: needs-tests

#1154 erpnext commit from 16 jan till 23 jan
  erpnext/__init__.py
  erpnext/accounts/doctype/accounts_settings/accounts_settings.js
  erpnext/accounts/doctype/accounts_settings/accounts_settings.json
  erpnext/accounts/doctype/accounts_settings/accounts_settings.py
  erpnext/accounts/doctype/pos_invoice/test_pos_invoice.py
  erpnext/accounts/doctype/subscription/subscription.py
  erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py
  erpnext/accounts/party.py
  erpnext/accounts/report/financial_statements.py
  erpnext/accounts/report/general_ledger/general_ledger.py
  erpnext/accounts/report/trial_balance/trial_balance.json
  erpnext/accounts/report/trial_balance/trial_balance.py
  erpnext/controllers/sales_and_purchase_return.py
  erpnext/controllers/taxes_and_totals.py
  erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.js
  erpnext/manufacturing/doctype/blanket_order/blanket_order.py
  erpnext/manufacturing/doctype/bom_creator/bom_creator.py
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
  erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.py
  erpnext/manufacturing/doctype/work_order/test_work_order.py
  erpnext/manufacturing/doctype/work_order/work_order.py
  erpnext/patches.txt
  erpnext/patches/v14_0/update_closing_balances.py
  erpnext/patches/v15_0/rename_manufacturing_settings_field.py
  erpnext/setup/utils.py
  erpnext/stock/doctype/pick_list/pick_list.py
  erpnext/stock/doctype/quality_inspection/quality_inspection.js
  erpnext/stock/doctype/quality_inspection/quality_inspection.json
  erpnext/stock/doctype/quality_inspection/quality_inspection.py
  erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
  erpnext/stock/report/stock_ageing/stock_ageing.py
  erpnext/stock/report/stock_ageing/test_stock_ageing.py
  erpnext/stock/serial_batch_bundle.py
Labels: Accounts, Stock

#1168 fix: item_wise_sale_register reort wrong total
  erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py
Labels: needs-tests
